"""add qkd seed column

Revision ID: 097be7581625
Revises: 0002_seeds
Create Date: 2026-08-22 15:13:00.186105
"""
from alembic import op
import sqlalchemy as sa


revision = '097be7581625'
down_revision = '0002_seeds'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qkd_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qkd_sessions', schema=None) as batch_op:
        batch_op.drop_column('seed')

    # ### end Alembic commands ###
