"""baseline schema per Section 11

Revision ID: 10e630a4bfa9
Revises: 
Create Date: 2026-08-22 12:23:40.633392
"""
from alembic import op
import sqlalchemy as sa


revision = '10e630a4bfa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_qubits', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocol_configs')),
    sa.UniqueConstraint('protocol', name=op.f('uq_protocol_configs_protocol'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_user_id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('USER','ATTACKER','ADMIN')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_unique_user_id'), ['unique_user_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('communication_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('session_status', sa.String(length=24), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_communication_sessions_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_communication_sessions_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_sessions'))
    )
    with op.batch_alter_table('communication_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_sessions_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index('ix_communication_sessions_receiver_status', ['receiver_id', 'session_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_sessions_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index('ix_communication_sessions_sender_status', ['sender_id', 'session_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_sessions_session_status'), ['session_status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('protocol_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_sessions.id'], name=op.f('fk_ai_recommendations_communication_id_communication_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_communication_id'), ['communication_id'], unique=False)

    op.create_table('attacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.String(length=32), nullable=False),
    sa.Column('attack_strength', sa.Float(), nullable=False),
    sa.Column('states_intercepted', sa.Integer(), nullable=False),
    sa.Column('states_modified', sa.Integer(), nullable=False),
    sa.Column('qber_before', sa.Float(), nullable=False),
    sa.Column('qber_after', sa.Float(), nullable=False),
    sa.Column('detection_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['users.id'], name=op.f('fk_attacks_attacker_id_users')),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_sessions.id'], name=op.f('fk_attacks_communication_id_communication_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attacks'))
    )
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attacks_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attacks_communication_id'), ['communication_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=True),
    sa.Column('encrypted_message', sa.Text(), nullable=True),
    sa.Column('nonce', sa.String(length=32), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qber', sa.Float(), nullable=True),
    sa.Column('key_status', sa.String(length=10), nullable=True),
    sa.Column('attack_detected', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_sessions.id'], name=op.f('fk_messages_communication_id_communication_sessions')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_communication_id'), ['communication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)

    op.create_table('qkd_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('qubits_generated', sa.Integer(), nullable=False),
    sa.Column('matching_bases', sa.Integer(), nullable=False),
    sa.Column('sifted_bits', sa.Integer(), nullable=False),
    sa.Column('compared_bits', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('qber', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('key_status', sa.String(length=10), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_sessions.id'], name=op.f('fk_qkd_sessions_communication_id_communication_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qkd_sessions'))
    )
    with op.batch_alter_table('qkd_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qkd_sessions_communication_id'), ['communication_id'], unique=False)

    op.create_table('secret_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('qkd_session_id', sa.Integer(), nullable=False),
    sa.Column('key_status', sa.String(length=10), nullable=False),
    sa.Column('key_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_sessions.id'], name=op.f('fk_secret_keys_communication_id_communication_sessions')),
    sa.ForeignKeyConstraint(['qkd_session_id'], ['qkd_sessions.id'], name=op.f('fk_secret_keys_qkd_session_id_qkd_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_keys'))
    )
    with op.batch_alter_table('secret_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_keys_communication_id'), ['communication_id'], unique=False)

    op.create_table('security_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('qber', sa.Float(), nullable=False),
    sa.Column('attack_detected', sa.Boolean(), nullable=False),
    sa.Column('key_status', sa.String(length=10), nullable=False),
    sa.Column('encryption_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_security_reports_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_reports'))
    )
    with op.batch_alter_table('security_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_reports_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_reports_message_id'))

    op.drop_table('security_reports')
    with op.batch_alter_table('secret_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_keys_communication_id'))

    op.drop_table('secret_keys')
    with op.batch_alter_table('qkd_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qkd_sessions_communication_id'))

    op.drop_table('qkd_sessions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_communication_id'))

    op.drop_table('messages')
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attacks_communication_id'))
        batch_op.drop_index(batch_op.f('ix_attacks_attacker_id'))

    op.drop_table('attacks')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_communication_id'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('communication_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_sessions_session_status'))
        batch_op.drop_index('ix_communication_sessions_sender_status')
        batch_op.drop_index(batch_op.f('ix_communication_sessions_sender_id'))
        batch_op.drop_index('ix_communication_sessions_receiver_status')
        batch_op.drop_index(batch_op.f('ix_communication_sessions_receiver_id'))

    op.drop_table('communication_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_unique_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('protocol_configs')
    # ### end Alembic commands ###
