"""communication_events + qkd sample_json

Revision ID: 6b029071db87
Revises: 0003_enable_all_protocols
Create Date: 2026-08-23 14:32:32.212483
"""
from alembic import op
import sqlalchemy as sa


revision = '6b029071db87'
down_revision = '0003_enable_all_protocols'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=True),
    sa.Column('previous_state', sa.String(length=24), nullable=True),
    sa.Column('actor_role', sa.String(length=12), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_sessions.id'], name=op.f('fk_communication_events_communication_id_communication_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_events'))
    )
    with op.batch_alter_table('communication_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_events_communication_id'), ['communication_id'], unique=False)

    with op.batch_alter_table('qkd_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qkd_sessions', schema=None) as batch_op:
        batch_op.drop_column('sample_json')

    with op.batch_alter_table('communication_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_events_communication_id'))

    op.drop_table('communication_events')
    # ### end Alembic commands ###
