import { Card, PageHeader } from "../../components/ui/Card";
import { Table, Td, Tr } from "../../components/ui/Table";
import { Badge } from "../../components/ui/StatusPill";
import { EmptyState, ErrorPanel, TableSkeleton } from "../../components/ui/Feedback";
import { useSecurityReport, useSecurityReports } from "../../queries/hooks";
import { useParams } from "react-router-dom";

function toneFor(r: { delivery_status: string; attack_detected: boolean }) {
  if (r.delivery_status === "BLOCKED" || r.attack_detected) return "danger" as const;
  if (r.delivery_status === "DELIVERED") return "success" as const;
  return "warning" as const;
}

/** F18 — list + per-message security report (backend-generated rows). */
export function SecurityReportsPage() {
  const { data, isPending, isError, error, refetch } = useSecurityReports();

  if (isError)
    return <ErrorPanel message={error.message} onRetry={() => refetch()} />;
  const rows = data?.items ?? [];

  return (
    <>
      <PageHeader
        title="Security reports"
        subtitle="One authoritative report per message, generated by the backend"
      />
      {isPending ? (
        <TableSkeleton cols={7} />
      ) : rows.length === 0 ? (
        <EmptyState title="No reports yet" hint="Reports appear after a message completes its pipeline." />
      ) : (
        <Table head={["Message", "Protocol", "QBER", "Threshold", "Key", "Delivery", "Generated"]}>
          {rows.map((r) => (
            <Tr key={`${r.message_id}-${r.created_at}`}>
              <Td className="font-mono text-xs">#{r.message_id}</Td>
              <Td className="font-mono text-xs">{r.protocol}</Td>
              <Td className="font-mono text-xs">{(r.qber * 100).toFixed(2)}%</Td>
              <Td className="font-mono text-xs">{(r.threshold * 100).toFixed(0)}%</Td>
              <Td><Badge tone={r.key_status === "ACCEPTED" ? "success" : r.key_status === "REJECTED" ? "danger" : "warning"}>{r.key_status}</Badge></Td>
              <Td><Badge tone={toneFor(r)}>{r.attack_detected ? "ATTACK DETECTED" : r.delivery_status}</Badge></Td>
              <Td className="text-xs text-muted">{new Date(r.created_at).toLocaleString()}</Td>
            </Tr>
          ))}
        </Table>
      )}
      <p className="mt-4 text-[11px] text-muted">
        Thresholds shown are simulation thresholds, not physics limits.
      </p>
    </>
  );
}

export function MessageSecurityReportPage() {
  const { id } = useParams();
  const messageId = id ? Number(id) : undefined;
  const { data, isPending, isError, error } = useSecurityReport(messageId);

  if (isPending)
    return (
      <>
        <PageHeader title="Security report" />
        <TableSkeleton cols={2} rows={6} />
      </>
    );
  if (isError || !data)
    return <ErrorPanel message={error?.message ?? "No security report exists yet."} code={(error as unknown as { code?: string })?.code} />;

  const r = data.report;
  return (
    <>
      <PageHeader
        title={`Security report · message #${r.message_id}`}
        subtitle={`Generated ${new Date(r.created_at).toLocaleString()}`}
      />
      <Card className="max-w-xl p-6">
        <dl className="space-y-3 text-sm">
          {[
            ["Protocol", r.protocol],
            ["QBER", `${(r.qber * 100).toFixed(2)}%`],
            ["Simulation threshold", `${(r.threshold * 100).toFixed(0)}%`],
            ["Key status", r.key_status],
            ["Attack detected", r.attack_detected ? "yes" : "no"],
            ["Encryption", r.encryption_status],
            ["Delivery", r.delivery_status],
          ].map(([k, v]) => (
            <div key={String(k)} className="flex items-center justify-between border-b border-border/60 pb-2">
              <dt className="text-muted">{k}</dt>
              <dd className="font-mono font-medium">{String(v)}</dd>
            </div>
          ))}
        </dl>
        <button
          onClick={() => window.print()}
          className="mt-5 rounded-md border border-border px-3 py-1.5 text-xs hover:border-primary"
        >
          Print report
        </button>
      </Card>
    </>
  );
}
